### ISSUE TITLE
Update addons.xml.md5

### ISSUE THREAD

**Issue by polojoe** [lastship/Lastship-Repo#1]
update of addons.xml.md5 is missing for latest update of lastship addon to 1.1.12
Thats why no updates are shown in kodi.

**Comment by Kr1ss-XD** [comment]
??   For sure addons.xml.md5 has been updated.   👓
https://github.com/lastship/Lastship-Repo/commit/d9f0ad8149b22688065e8834492ba9d6b8dca239
Addon update through repo is working...
