### ISSUE TITLE
Kodi 18 Suchfunktion

### ISSUE THREAD

**Issue by metaiiica** [lastship/Lastship-Repo#4]
### Actual Behavior / Tatsächliches Verhalten :
Seit Kodi 18 ab etwa 01.05.2018 funktioniert die Film und Seriensuchfunktion nicht mehr
Getestet mit LibreElec, OpenElec und Android 7.1(S912) und Samsung Galaxy S9+ (Android 8.0)

jede Version mit Kodi 18 vor dem 01.05.18 hat dieses Problem nicht erst ab diesem Datum

### Steps to Reproduce / Schritte zur Reproduktion :
Installiere neueste Kodi 18
Starte Lastship
geh zu Suche
such einen Film, zB. Avatar

es passiert danach nichts mehr, der Suchbegriff wird aber hinzugefügt. Auch ein erneuter Aufruf des Begriffs (auch mit einem Neustart oder frischer Installation)

#### Additional Information / Weitere Informationen :
Covenant ist ebenso betroffen

###### Hardware, Kodi Version, Lastship Version :
Kodi 18 ab 01.05.2018
letzte Lastship Version und letzter URL-Resolver
###### Environment (additional Hardware, OS, ...) 
TV-Box KM8-P S912 Android 7.1, LibreElec, OpenElec
Samsung Galaxy S9+ Android 8.0 
/ Umgebung (zusätzl. Hardware, Betriebssystem, ...) :

##### **(Link to / Link zum) Debug-Logfile** :

- - -

**Comment by BRainXstorming** [comment]
Hab einen kleinen workarround gefunden. Du musst in den Einstellungen von Last ship schnell suche einstellen. Du kannst dann nur direkt über das Hauptmenü von Last ship suchen. Wenn du zuerst auf Filme gehst und dann suche geht es nicht. Ärgerlich dabei ist, dass man halt immer wieder erneut den Text eingeben muss, da die suchhistorie nicht funktioniert.
