### ISSUE TITLE
Request to remove DuckDuckGo querying

### ISSUE THREAD

**Issue by tagawa** [lastship/Lastship-Repo#5]
Guten Tag.

This is Daniel from DuckDuckGo. I'm just writing regarding the use of querying our search results in Lastship. This isn't a valid use of our service as we use a variety of sources to get results, and we don’t have syndication rights for some of these. That means that this type of behavior is considered abusive by our upstream providers (and subsequently us). You're welcome to use our public API, however (described here: https://api.duckduckgo.com ).

Thank you for your understanding and please let me know if you have questions.

**Comment by merlux** [comment]
Hi Daniel,
We will remove the querying the next days and replace it with your suggested API. Thanks for reaching out to us instead of blocking. The rollout will then also happen soon.

**Comment by tagawa** [comment]
Hi @merlux. I really appreciate you getting back to me. Thank you, and we'll look out for the changes.

**Comment by tagawa** [comment]
Hi again. It looks like this change has been made and released - thank you!
