### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by charona** [lastship/Lastship-Repo#8]
Trying to install from zip file. System: Raspberry Pi4 with LibreELEC (set up from latest release yesterday). Error message: Failed to install add-on from zip file.

I have installed other add-on zips without problems.

Any ideas?

**Comment by anis3** [comment]
Lastship is dead use xStream
https://github.com/streamxstream/xStreamRepo/tree/master/repository.xstream

**Comment by charona** [comment]
Thanks. Link above contains 2 images and an XML. Real content seems to be here:
https://github.com/streamxstream/xStreamRepo
(sorry, I'm pretty new to both Github and Kodin).
